// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisCourt.Models;

namespace TennisCourt.Migrations
{
    [DbContext(typeof(TennisCourtContext))]
    partial class TennisCourtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TennisCourt.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Public")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SurfaceType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CourtId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            CourtId = 3,
                            Address = "1111 Interlake N",
                            City = "Seattle",
                            Name = "Seattle Tennis Club",
                            Public = true,
                            State = "Washington",
                            SurfaceType = "Hard"
                        },
                        new
                        {
                            CourtId = 4,
                            Address = "2314 Denny way N",
                            City = "Fargo",
                            Name = "Fargo Community Center",
                            Public = true,
                            State = "North Dakota",
                            SurfaceType = "Grass"
                        },
                        new
                        {
                            CourtId = 5,
                            Address = "700 Rex st SE",
                            City = "Portland",
                            Name = "Portland University Court",
                            Public = true,
                            State = "Oregon",
                            SurfaceType = "Hard"
                        },
                        new
                        {
                            CourtId = 6,
                            Address = "1245 Spokane Way N",
                            City = "Spokane",
                            Name = "Spokane Court",
                            Public = true,
                            State = "Washington",
                            SurfaceType = "Hard"
                        },
                        new
                        {
                            CourtId = 7,
                            Address = "435 Lynn S",
                            City = "San Francisco",
                            Name = "San Francisco Tennis Club",
                            Public = false,
                            State = "California",
                            SurfaceType = "Clay"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
